-- Ensure api schema exists
CREATE SCHEMA IF NOT EXISTS api;

-- Function to generate a random 16-character string in api schema
CREATE OR REPLACE FUNCTION api.generate_random_code()
RETURNS TEXT AS $$
DECLARE
  chars TEXT := 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  result TEXT := '';
  i INTEGER;
BEGIN
  FOR i IN 1..16 LOOP
    result := result || substr(chars, floor(random() * length(chars) + 1)::integer, 1);
  END LOOP;
  RETURN result;
END;
$$ LANGUAGE plpgsql;

-- Create the demo_codes table in api schema
CREATE TABLE IF NOT EXISTS api.demo_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT NOT NULL UNIQUE DEFAULT api.generate_random_code(),
  last_use TIMESTAMPTZ,
  role TEXT NOT NULL,
  notes TEXT
);

-- Add notes column if table already exists (migration)
DO $$ 
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'api' AND table_name = 'demo_codes') THEN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'api' AND table_name = 'demo_codes' AND column_name = 'notes') THEN
      ALTER TABLE api.demo_codes ADD COLUMN notes TEXT;
    END IF;
  END IF;
END $$;

-- Create an index on code for faster lookups
CREATE INDEX IF NOT EXISTS idx_demo_codes_code ON api.demo_codes(code);

-- Enable Row Level Security
ALTER TABLE api.demo_codes ENABLE ROW LEVEL SECURITY;

-- RPC function to authenticate with demo code and update last_use
CREATE OR REPLACE FUNCTION api.authenticate_demo_code(code_input TEXT)
RETURNS TABLE (
  id UUID,
  code TEXT,
  role TEXT,
  last_use TIMESTAMPTZ,
  notes TEXT
) AS $$
DECLARE
  code_record RECORD;
BEGIN
  -- Find and lock the row for update
  SELECT * INTO code_record
  FROM api.demo_codes
  WHERE api.demo_codes.code = code_input
  FOR UPDATE;
  
  -- If code not found, return nothing
  IF NOT FOUND THEN
    RETURN;
  END IF;
  
  -- Update last_use timestamp
  UPDATE api.demo_codes
  SET last_use = NOW()
  WHERE api.demo_codes.id = code_record.id;
  
  -- Return the updated record
  RETURN QUERY
  SELECT 
    code_record.id,
    code_record.code,
    code_record.role,
    NOW() as last_use,
    code_record.notes;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute permission to authenticated users (or anon if needed)
GRANT EXECUTE ON FUNCTION api.authenticate_demo_code(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION api.authenticate_demo_code(TEXT) TO anon;
GRANT EXECUTE ON FUNCTION api.authenticate_demo_code(TEXT) TO service_role;

-- Create a public wrapper function for Supabase RPC (Supabase RPC calls look in public schema)
CREATE OR REPLACE FUNCTION public.authenticate_demo_code(code_input TEXT)
RETURNS TABLE (
  id UUID,
  code TEXT,
  role TEXT,
  last_use TIMESTAMPTZ,
  notes TEXT
) AS $$
BEGIN
  RETURN QUERY
  SELECT * FROM api.authenticate_demo_code(code_input);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute permission on the public wrapper
GRANT EXECUTE ON FUNCTION public.authenticate_demo_code(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.authenticate_demo_code(TEXT) TO anon;
GRANT EXECUTE ON FUNCTION public.authenticate_demo_code(TEXT) TO service_role;

-- Optional: Add comments to the table
COMMENT ON TABLE api.demo_codes IS 'Table for demo authentication codes';
COMMENT ON COLUMN api.demo_codes.code IS '16-character random string generated by default';
COMMENT ON COLUMN api.demo_codes.role IS 'User role assigned to this demo code';
COMMENT ON COLUMN api.demo_codes.notes IS 'Internal notes for admin tracking purposes';
COMMENT ON FUNCTION api.authenticate_demo_code IS 'Authenticates a demo code and updates the last_use timestamp';

